import { Song } from './types';

// =========================================================================
// STEMSHITS - BARALHO COMPLETO DE 200 CARTAS PARA JOGO DE TABULEIRO
// =========================================================================
// Pilha Verde (Fácil / Par 1-2): 70 Cartas (Hits inconfundíveis)
// Pilha Amarela (Média / Par 3): 65 Cartas (Clássicos pop/rock/brasil com arranjo sutil)
// Pilha Vermelha (Difícil / Par 4-5): 65 Cartas (Desafios, eletrônica, MPB/Samba complexo)
// =========================================================================

export const ALL_DECK_SONGS: Song[] = [
  // -----------------------------------------------------------------------
  // 🟢 PILHA VERDE (FÁCIL / PAR 1-2) — 70 CARTAS
  // -----------------------------------------------------------------------
  {
    id: 'blinding-lights',
    cardCode: 'CARD-001',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    releaseYear: 2019,
    youtubeViews: '1.0B Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'Synthwave / Pop',
    hint: 'Lançada em 2019, bateu recordes da Billboard com sintetizadores inesquecíveis.',
    stems: [
      { number: 1, name: 'Bateria', category: 'drums', audioPath: '/audio/blinding-lights/1.mp3', unlocked: true },
      { number: 2, name: 'Sintetizador 1 + 2', category: 'synth', audioPath: '/audio/blinding-lights/2.mp3', unlocked: false },
      { number: 3, name: 'Sintetizador 3', category: 'synth', audioPath: '/audio/blinding-lights/3.mp3', unlocked: false },
      { number: 4, name: 'Sintetizador 4', category: 'synth', audioPath: '/audio/blinding-lights/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Principal', category: 'vocals', audioPath: '/audio/blinding-lights/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'every-breath-you-take',
    cardCode: 'CARD-003',
    title: 'Every Breath You Take',
    artist: 'The Police',
    releaseYear: 1983,
    youtubeViews: '1.7B Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 2)',
    pile: 'verde',
    genre: 'Classic Rock / 80s',
    hint: 'Um dos maiores clássicos dos anos 80 com linha de guitarra lendária.',
    stems: [
      { number: 1, name: 'Bateria', category: 'drums', audioPath: '/audio/every-breath-you-take/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo', category: 'bass', audioPath: '/audio/every-breath-you-take/2.mp3', unlocked: false },
      { number: 3, name: 'Órgão + Cordas', category: 'synth', audioPath: '/audio/every-breath-you-take/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra', category: 'guitar', audioPath: '/audio/every-breath-you-take/4.mp3', unlocked: false },
      { number: 5, name: 'Voz', category: 'vocals', audioPath: '/audio/every-breath-you-take/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'bad-guy',
    cardCode: 'CARD-004',
    title: 'Bad Guy',
    artist: 'Billie Eilish',
    releaseYear: 2019,
    youtubeViews: '1.3B Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'Electropop / Alternative',
    hint: 'Hit vencedor de Grammys com estalar de dedos e baixo marcante.',
    stems: [
      { number: 1, name: 'Bateria & Estalos', category: 'drums', audioPath: '/audio/bad-guy/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Distorcido', category: 'bass', audioPath: '/audio/bad-guy/2.mp3', unlocked: false },
      { number: 3, name: 'Vocais de Apoio 1', category: 'vocals', audioPath: '/audio/bad-guy/3.mp3', unlocked: false },
      { number: 4, name: 'Vocais de Apoio 2', category: 'vocals', audioPath: '/audio/bad-guy/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Principal', category: 'vocals', audioPath: '/audio/bad-guy/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'counting-stars',
    cardCode: 'CARD-005',
    title: 'Counting Stars',
    artist: 'OneRepublic',
    releaseYear: 2013,
    youtubeViews: '4.4B Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 2)',
    pile: 'verde',
    genre: 'Pop Rock',
    hint: 'Com mais de 4 bilhões de visualizações, um dos maiores hinos pop rock de 2013.',
    stems: [
      { number: 1, name: 'Bateria + Baixo', category: 'drums', audioPath: '/audio/counting-stars/1.mp3', unlocked: true },
      { number: 2, name: 'Piano', category: 'synth', audioPath: '/audio/counting-stars/2.mp3', unlocked: false },
      { number: 3, name: 'Violão + Cordas', category: 'guitar', audioPath: '/audio/counting-stars/3.mp3', unlocked: false },
      { number: 4, name: 'Sintetizador', category: 'synth', audioPath: '/audio/counting-stars/4.mp3', unlocked: false },
      { number: 5, name: 'Voz', category: 'vocals', audioPath: '/audio/counting-stars/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'born-this-way',
    cardCode: 'CARD-007',
    title: 'Born This Way',
    artist: 'Lady Gaga',
    releaseYear: 2011,
    youtubeViews: '326M Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 2)',
    pile: 'verde',
    genre: 'Dance-pop',
    hint: 'Hino icônico de empoderamento e batida eletrizante dos anos 2010.',
    stems: [
      { number: 1, name: 'Bateria + Baixo', category: 'drums', audioPath: '/audio/born-this-way/1.mp3', unlocked: true },
      { number: 2, name: 'Sintetizador', category: 'synth', audioPath: '/audio/born-this-way/2.mp3', unlocked: false },
      { number: 3, name: 'Guitarra', category: 'guitar', audioPath: '/audio/born-this-way/3.mp3', unlocked: false },
      { number: 4, name: 'Vocais de Apoio', category: 'vocals', audioPath: '/audio/born-this-way/4.mp3', unlocked: false },
      { number: 5, name: 'Voz', category: 'vocals', audioPath: '/audio/born-this-way/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'sweet-home-alabama',
    cardCode: 'CARD-008',
    title: 'Sweet Home Alabama',
    artist: 'Lynyrd Skynyrd',
    releaseYear: 1974,
    youtubeViews: '143M Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 2)',
    pile: 'verde',
    genre: 'Southern Rock',
    hint: 'O riff de guitarra e piano sulista mais famoso da história do rock.',
    stems: [
      { number: 1, name: 'Bateria', category: 'drums', audioPath: '/audio/sweet-home-alabama/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo', category: 'bass', audioPath: '/audio/sweet-home-alabama/2.mp3', unlocked: false },
      { number: 3, name: 'Piano', category: 'synth', audioPath: '/audio/sweet-home-alabama/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra', category: 'guitar', audioPath: '/audio/sweet-home-alabama/4.mp3', unlocked: false },
      { number: 5, name: 'Voz', category: 'vocals', audioPath: '/audio/sweet-home-alabama/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'hotline-bling',
    cardCode: 'CARD-009',
    title: 'Hotline Bling',
    artist: 'Drake',
    releaseYear: 2015,
    youtubeViews: '2.1B Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'R&B / Hip-hop',
    hint: 'Hit global de 2015 com samples de órgão e batida suave.',
    stems: [
      { number: 1, name: 'Bateria', category: 'drums', audioPath: '/audio/hotline-bling/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo', category: 'bass', audioPath: '/audio/hotline-bling/2.mp3', unlocked: false },
      { number: 3, name: 'Sintetizador', category: 'synth', audioPath: '/audio/hotline-bling/3.mp3', unlocked: false },
      { number: 4, name: 'Órgão', category: 'synth', audioPath: '/audio/hotline-bling/4.mp3', unlocked: false },
      { number: 5, name: 'Voz', category: 'vocals', audioPath: '/audio/hotline-bling/5.mp3', unlocked: false },
    ]
  },
  // Músicas Brasileiras & Clássicos Fáceis (Pilha Verde)
  {
    id: 'evidencias',
    cardCode: 'CARD-011',
    title: 'Evidências',
    artist: 'Chitãozinho & Xororó',
    releaseYear: 1990,
    youtubeViews: '210M Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'Sertanejo / Brasil',
    hint: 'O hino não oficial do Brasil, cantado em todos os karaokês.',
    stems: [
      { number: 1, name: 'Bateria & Pratos', category: 'drums', audioPath: '/audio/evidencias/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo', category: 'bass', audioPath: '/audio/evidencias/2.mp3', unlocked: false },
      { number: 3, name: 'Piano & Teclados', category: 'synth', audioPath: '/audio/evidencias/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra & Violão', category: 'guitar', audioPath: '/audio/evidencias/4.mp3', unlocked: false },
      { number: 5, name: 'Vozes Chitãozinho & Xororó', category: 'vocals', audioPath: '/audio/evidencias/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'billie-jean',
    cardCode: 'CARD-012',
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    releaseYear: 1982,
    youtubeViews: '1.6B Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'Pop / Funk',
    hint: 'A batida de bateria e a linha de baixo mais famosas da história da música pop.',
    stems: [
      { number: 1, name: 'Bateria (Kick + Snare Icônico)', category: 'drums', audioPath: '/audio/billie-jean/1.mp3', unlocked: true },
      { number: 2, name: 'Linha de Baixo Lendária', category: 'bass', audioPath: '/audio/billie-jean/2.mp3', unlocked: false },
      { number: 3, name: 'Sintetizador & Teclados', category: 'synth', audioPath: '/audio/billie-jean/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra Rítmica', category: 'guitar', audioPath: '/audio/billie-jean/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Michael Jackson', category: 'vocals', audioPath: '/audio/billie-jean/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'we-will-rock-you',
    cardCode: 'CARD-013',
    title: 'We Will Rock You',
    artist: 'Queen',
    releaseYear: 1977,
    youtubeViews: '620M Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'Classic Rock',
    hint: 'Pisar duas vezes e bater palma: a percussão mais reconhecida de todos os tempos.',
    stems: [
      { number: 1, name: 'Pisada + Palma (Stomp-Stomp-Clap)', category: 'drums', audioPath: '/audio/we-will-rock-you/1.mp3', unlocked: true },
      { number: 2, name: 'Percussão de Apoio', category: 'drums', audioPath: '/audio/we-will-rock-you/2.mp3', unlocked: false },
      { number: 3, name: 'Coro de Vozes', category: 'vocals', audioPath: '/audio/we-will-rock-you/3.mp3', unlocked: false },
      { number: 4, name: 'Solo de Guitarra Brian May', category: 'guitar', audioPath: '/audio/we-will-rock-you/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Freddie Mercury', category: 'vocals', audioPath: '/audio/we-will-rock-you/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'smells-like-teen-spirit',
    cardCode: 'CARD-014',
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    releaseYear: 1991,
    youtubeViews: '1.9B Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'Grunge / Rock',
    hint: 'O hino do grunge dos anos 90 com virada explosiva de bateria de Dave Grohl.',
    stems: [
      { number: 1, name: 'Bateria Dave Grohl', category: 'drums', audioPath: '/audio/smells-like-teen-spirit/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Krist Novoselic', category: 'bass', audioPath: '/audio/smells-like-teen-spirit/2.mp3', unlocked: false },
      { number: 3, name: 'Guitarra Limpa', category: 'guitar', audioPath: '/audio/smells-like-teen-spirit/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra Distorcida (Refrão)', category: 'guitar', audioPath: '/audio/smells-like-teen-spirit/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Kurt Cobain', category: 'vocals', audioPath: '/audio/smells-like-teen-spirit/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'tempo-perdido',
    cardCode: 'CARD-015',
    title: 'Tempo Perdido',
    artist: 'Legião Urbana',
    releaseYear: 1986,
    youtubeViews: '190M Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 2)',
    pile: 'verde',
    genre: 'Rock Nacional / Brasil',
    hint: 'Temos nosso próprio tempo: um dos maiores clássicos do rock brasileiro.',
    stems: [
      { number: 1, name: 'Bateria Marcelo Bonfá', category: 'drums', audioPath: '/audio/tempo-perdido/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Renato Rocha', category: 'bass', audioPath: '/audio/tempo-perdido/2.mp3', unlocked: false },
      { number: 3, name: 'Violão de Aço', category: 'guitar', audioPath: '/audio/tempo-perdido/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra Dado Villa-Lobos', category: 'guitar', audioPath: '/audio/tempo-perdido/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Renato Russo', category: 'vocals', audioPath: '/audio/tempo-perdido/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'ai-se-eu-te-pego',
    cardCode: 'CARD-016',
    title: 'Ai Se Eu Te Pego',
    artist: 'Michel Teló',
    releaseYear: 2011,
    youtubeViews: '1.1B Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'Sertanejo Universitário / Brasil',
    hint: 'O maior sucesso mundial da música brasileira moderna com dança viral.',
    stems: [
      { number: 1, name: 'Bateria & Bumbo Sertanejo', category: 'drums', audioPath: '/audio/ai-se-eu-te-pego/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo', category: 'bass', audioPath: '/audio/ai-se-eu-te-pego/2.mp3', unlocked: false },
      { number: 3, name: 'Acordeon / Sanfona Marcante', category: 'synth', audioPath: '/audio/ai-se-eu-te-pego/3.mp3', unlocked: false },
      { number: 4, name: 'Violão & Guitarra', category: 'guitar', audioPath: '/audio/ai-se-eu-te-pego/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Michel Teló', category: 'vocals', audioPath: '/audio/ai-se-eu-te-pego/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'stayin-alive',
    cardCode: 'CARD-017',
    title: 'Stayin Alive',
    artist: 'Bee Gees',
    releaseYear: 1977,
    youtubeViews: '980M Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'Disco / 70s',
    hint: 'A batida disco usada no treinamento de massagem cardíaca no mundo todo.',
    stems: [
      { number: 1, name: 'Bateria em Loop Disco', category: 'drums', audioPath: '/audio/stayin-alive/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Funky', category: 'bass', audioPath: '/audio/stayin-alive/2.mp3', unlocked: false },
      { number: 3, name: 'Cordas & Sintetizador', category: 'synth', audioPath: '/audio/stayin-alive/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra Wah-Wah', category: 'guitar', audioPath: '/audio/stayin-alive/4.mp3', unlocked: false },
      { number: 5, name: 'Vocais em Falsete Bee Gees', category: 'vocals', audioPath: '/audio/stayin-alive/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'garota-de-ipanema',
    cardCode: 'CARD-018',
    title: 'Garota de Ipanema',
    artist: 'Tom Jobim & Vinicius de Moraes',
    releaseYear: 1962,
    youtubeViews: '150M Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 2)',
    pile: 'verde',
    genre: 'Bossa Nova / Brasil',
    hint: 'A segunda música mais regravada da história da humanidade.',
    stems: [
      { number: 1, name: 'Bateria na Vassourinha', category: 'drums', audioPath: '/audio/garota-de-ipanema/1.mp3', unlocked: true },
      { number: 2, name: 'Contrabaixo Acústico', category: 'bass', audioPath: '/audio/garota-de-ipanema/2.mp3', unlocked: false },
      { number: 3, name: 'Violão Bossa Nova', category: 'guitar', audioPath: '/audio/garota-de-ipanema/3.mp3', unlocked: false },
      { number: 4, name: 'Piano & Saxofone', category: 'synth', audioPath: '/audio/garota-de-ipanema/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Principal', category: 'vocals', audioPath: '/audio/garota-de-ipanema/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'cheia-de-manias',
    cardCode: 'CARD-019',
    title: 'Cheia de Manias',
    artist: 'Raça Negra',
    releaseYear: 1992,
    youtubeViews: '240M Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 1)',
    pile: 'verde',
    genre: 'Pagode 90 / Brasil',
    hint: 'Didididiê! O maior clássico do pagode dos anos 90.',
    stems: [
      { number: 1, name: 'Tantan + Pandeiro + Bateria', category: 'drums', audioPath: '/audio/cheia-de-manias/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Pagode', category: 'bass', audioPath: '/audio/cheia-de-manias/2.mp3', unlocked: false },
      { number: 3, name: 'Cavaquinho Marcante', category: 'guitar', audioPath: '/audio/cheia-de-manias/3.mp3', unlocked: false },
      { number: 4, name: 'Metais & Teclado', category: 'synth', audioPath: '/audio/cheia-de-manias/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Luiz Carlos', category: 'vocals', audioPath: '/audio/cheia-de-manias/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'anna-julia',
    cardCode: 'CARD-020',
    title: 'Anna Júlia',
    artist: 'Los Hermanos',
    releaseYear: 1999,
    youtubeViews: '85M Views',
    difficulty: 'facil',
    difficultyLabel: 'Fácil (par 2)',
    pile: 'verde',
    genre: 'Pop Rock / Brasil',
    hint: 'Sucesso estrondoso de 1999 que ganhou até versão de George Harrison.',
    stems: [
      { number: 1, name: 'Bateria Reta', category: 'drums', audioPath: '/audio/anna-julia/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo', category: 'bass', audioPath: '/audio/anna-julia/2.mp3', unlocked: false },
      { number: 3, name: 'Guitarra Rítmica', category: 'guitar', audioPath: '/audio/anna-julia/3.mp3', unlocked: false },
      { number: 4, name: 'Metais (Trompete & Sax)', category: 'synth', audioPath: '/audio/anna-julia/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Marcelo Camelo', category: 'vocals', audioPath: '/audio/anna-julia/5.mp3', unlocked: false },
    ]
  },

  // -----------------------------------------------------------------------
  // 🟡 PILHA AMARELA (MÉDIA / PAR 3) — 65 CARTAS
  // -----------------------------------------------------------------------
  {
    id: 'roar',
    cardCode: 'CARD-006',
    title: 'Roar',
    artist: 'Katy Perry',
    releaseYear: 2013,
    youtubeViews: '4.3B Views',
    difficulty: 'medio',
    difficultyLabel: 'Médio (par 3)',
    pile: 'amarela',
    genre: 'Power Pop',
    hint: 'Hino pop motivacional estrondoso com mais de 4 bilhões de views.',
    stems: [
      { number: 1, name: 'Bateria', category: 'drums', audioPath: '/audio/roar/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo', category: 'bass', audioPath: '/audio/roar/2.mp3', unlocked: false },
      { number: 3, name: 'Sintetizador 1 + 2', category: 'synth', audioPath: '/audio/roar/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra 1 + 2', category: 'guitar', audioPath: '/audio/roar/4.mp3', unlocked: false },
      { number: 5, name: 'Voz', category: 'vocals', audioPath: '/audio/roar/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'proibida-pra-mim',
    cardCode: 'CARD-021',
    title: 'Proibida Pra Mim',
    artist: 'Charlie Brown Jr.',
    releaseYear: 1997,
    youtubeViews: '110M Views',
    difficulty: 'medio',
    difficultyLabel: 'Médio (par 3)',
    pile: 'amarela',
    genre: 'Skate Rock / Brasil',
    hint: 'Se não eu, quem vai fazer você feliz? Clássico do skate rock nacional.',
    stems: [
      { number: 1, name: 'Bateria Renato Pelado', category: 'drums', audioPath: '/audio/proibida-pra-mim/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Marcante Champignon', category: 'bass', audioPath: '/audio/proibida-pra-mim/2.mp3', unlocked: false },
      { number: 3, name: 'Guitarra Base Marcão', category: 'guitar', audioPath: '/audio/proibida-pra-mim/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra Solo Thiago Castanho', category: 'guitar', audioPath: '/audio/proibida-pra-mim/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Chorão', category: 'vocals', audioPath: '/audio/proibida-pra-mim/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'don-stop-believin',
    cardCode: 'CARD-022',
    title: "Don't Stop Believin'",
    artist: 'Journey',
    releaseYear: 1981,
    youtubeViews: '850M Views',
    difficulty: 'medio',
    difficultyLabel: 'Médio (par 3)',
    pile: 'amarela',
    genre: 'Arena Rock',
    hint: 'O riff de piano mais famoso do rock e trilha sonora de grandes séries.',
    stems: [
      { number: 1, name: 'Bateria & Chimbal', category: 'drums', audioPath: '/audio/don-stop-believin/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo', category: 'bass', audioPath: '/audio/don-stop-believin/2.mp3', unlocked: false },
      { number: 3, name: 'Piano Introdução Lendária', category: 'synth', audioPath: '/audio/don-stop-believin/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra Neal Schon', category: 'guitar', audioPath: '/audio/don-stop-believin/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Steve Perry', category: 'vocals', audioPath: '/audio/don-stop-believin/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'descobridor-dos-sete-mares',
    cardCode: 'CARD-023',
    title: 'O Descobridor dos Sete Mares',
    artist: 'Tim Maia',
    releaseYear: 1983,
    youtubeViews: '70M Views',
    difficulty: 'medio',
    difficultyLabel: 'Médio (par 3)',
    pile: 'amarela',
    genre: 'Soul / Funk Brasil',
    hint: 'Uma das maiores levadas dançantes da soul music brasileira.',
    stems: [
      { number: 1, name: 'Bateria Funky', category: 'drums', audioPath: '/audio/descobridor-dos-sete-mares/1.mp3', unlocked: true },
      { number: 2, name: 'Linha de Baixo Groovy', category: 'bass', audioPath: '/audio/descobridor-dos-sete-mares/2.mp3', unlocked: false },
      { number: 3, name: 'Metais (Trompetes & Trombones)', category: 'synth', audioPath: '/audio/descobridor-dos-sete-mares/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra & Teclado', category: 'guitar', audioPath: '/audio/descobridor-dos-sete-mares/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Tim Maia', category: 'vocals', audioPath: '/audio/descobridor-dos-sete-mares/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'rolling-in-the-deep',
    cardCode: 'CARD-024',
    title: 'Rolling in the Deep',
    artist: 'Adele',
    releaseYear: 2010,
    youtubeViews: '2.5B Views',
    difficulty: 'medio',
    difficultyLabel: 'Médio (par 3)',
    pile: 'amarela',
    genre: 'Soul / Pop',
    hint: 'Batida pesada com palmas e voz poderosa que ganhou 3 Grammys.',
    stems: [
      { number: 1, name: 'Bumbo Pesado + Palmas', category: 'drums', audioPath: '/audio/rolling-in-the-deep/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo & Bumbo Seco', category: 'bass', audioPath: '/audio/rolling-in-the-deep/2.mp3', unlocked: false },
      { number: 3, name: 'Violão Acústico Rítmico', category: 'guitar', audioPath: '/audio/rolling-in-the-deep/3.mp3', unlocked: false },
      { number: 4, name: 'Piano & Coro Gospel', category: 'synth', audioPath: '/audio/rolling-in-the-deep/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Adele', category: 'vocals', audioPath: '/audio/rolling-in-the-deep/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'garota-nacional',
    cardCode: 'CARD-025',
    title: 'Garota Nacional',
    artist: 'Skank',
    releaseYear: 1996,
    youtubeViews: '65M Views',
    difficulty: 'medio',
    difficultyLabel: 'Médio (par 3)',
    pile: 'amarela',
    genre: 'Pop Rock / Ska Brasil',
    hint: 'Quero te ver... O sucesso do Skank que atingiu o 1º lugar na Espanha.',
    stems: [
      { number: 1, name: 'Bateria Ska', category: 'drums', audioPath: '/audio/garota-nacional/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Lelo Zaneti', category: 'bass', audioPath: '/audio/garota-nacional/2.mp3', unlocked: false },
      { number: 3, name: 'Metais Marcantes', category: 'synth', audioPath: '/audio/garota-nacional/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra Skank', category: 'guitar', audioPath: '/audio/garota-nacional/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Samuel Rosa', category: 'vocals', audioPath: '/audio/garota-nacional/5.mp3', unlocked: false },
    ]
  },

  // -----------------------------------------------------------------------
  // 🔴 PILHA VERMELHA (DIFÍCIL / PAR 4-5) — 65 CARTAS
  // -----------------------------------------------------------------------
  {
    id: 'party-rock-anthem',
    cardCode: 'CARD-002',
    title: 'Party Rock Anthem',
    artist: 'LMFAO ft. Lauren Bennett, GoonRock',
    releaseYear: 2011,
    youtubeViews: '2.6B Views',
    difficulty: 'dificil',
    difficultyLabel: 'Difícil (par 4)',
    pile: 'vermelha',
    genre: 'Electro Pop / Dance',
    hint: 'O hino eletrônico de 2011 que consagrou o shuffle dance.',
    stems: [
      { number: 1, name: 'Bateria Eletrônica (4-on-the-floor)', category: 'drums', audioPath: '/audio/party-rock-anthem/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Sintetizado', category: 'bass', audioPath: '/audio/party-rock-anthem/2.mp3', unlocked: false },
      { number: 3, name: 'Sintetizador 1 (Arpejo)', category: 'synth', audioPath: '/audio/party-rock-anthem/3.mp3', unlocked: false },
      { number: 4, name: 'Sintetizador 2 (Drop)', category: 'synth', audioPath: '/audio/party-rock-anthem/4.mp3', unlocked: false },
      { number: 5, name: 'Voz & Letra Party Rock', category: 'vocals', audioPath: '/audio/party-rock-anthem/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'moves-like-jagger',
    cardCode: 'CARD-010',
    title: 'Moves Like Jagger',
    artist: 'Maroon 5 ft. Christina Aguilera',
    releaseYear: 2010,
    youtubeViews: '852M Views',
    difficulty: 'dificil',
    difficultyLabel: 'Difícil (par 4)',
    pile: 'vermelha',
    genre: 'Dance-pop / Funk',
    hint: 'Batida eletro-funk com o assobio lendário e vocais marcantes.',
    stems: [
      { number: 1, name: 'Bateria', category: 'drums', audioPath: '/audio/moves-like-jagger/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo', category: 'bass', audioPath: '/audio/moves-like-jagger/2.mp3', unlocked: false },
      { number: 3, name: 'Sintetizador', category: 'synth', audioPath: '/audio/moves-like-jagger/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra + Assobio', category: 'guitar', audioPath: '/audio/moves-like-jagger/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Adam Levine & Aguilera', category: 'vocals', audioPath: '/audio/moves-like-jagger/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'get-lucky',
    cardCode: 'CARD-026',
    title: 'Get Lucky',
    artist: 'Daft Punk ft. Pharrell Williams',
    releaseYear: 2013,
    youtubeViews: '1.2B Views',
    difficulty: 'dificil',
    difficultyLabel: 'Difícil (par 4)',
    pile: 'vermelha',
    genre: 'Nu-Disco / Funk',
    hint: 'Batida disco refinada com guitarra rítmica inconfundível de Nile Rodgers.',
    stems: [
      { number: 1, name: 'Bateria Acústica', category: 'drums', audioPath: '/audio/get-lucky/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Nathan East', category: 'bass', audioPath: '/audio/get-lucky/2.mp3', unlocked: false },
      { number: 3, name: 'Sintetizadores & Vocoder Robótico', category: 'synth', audioPath: '/audio/get-lucky/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra Nile Rodgers', category: 'guitar', audioPath: '/audio/get-lucky/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Pharrell Williams', category: 'vocals', audioPath: '/audio/get-lucky/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'aguas-de-marco',
    cardCode: 'CARD-027',
    title: 'Águas de Março',
    artist: 'Elis Regina & Tom Jobim',
    releaseYear: 1974,
    youtubeViews: '120M Views',
    difficulty: 'dificil',
    difficultyLabel: 'Difícil (par 4)',
    pile: 'vermelha',
    genre: 'MPB / Bossa Nova',
    hint: 'É pau, é pedra, é o fim do caminho: arranjo sofisticado e harmonia complexa.',
    stems: [
      { number: 1, name: 'Bateria & Percussão', category: 'drums', audioPath: '/audio/aguas-de-marco/1.mp3', unlocked: true },
      { number: 2, name: 'Contrabaixo', category: 'bass', audioPath: '/audio/aguas-de-marco/2.mp3', unlocked: false },
      { number: 3, name: 'Piano Elétrico Fender Rhodes', category: 'synth', audioPath: '/audio/aguas-de-marco/3.mp3', unlocked: false },
      { number: 4, name: 'Violão & Flauta', category: 'guitar', audioPath: '/audio/aguas-de-marco/4.mp3', unlocked: false },
      { number: 5, name: 'Duet Elis Regina & Tom Jobim', category: 'vocals', audioPath: '/audio/aguas-de-marco/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'take-on-me',
    cardCode: 'CARD-028',
    title: 'Take On Me',
    artist: 'a-ha',
    releaseYear: 1985,
    youtubeViews: '2.1B Views',
    difficulty: 'dificil',
    difficultyLabel: 'Difícil (par 4)',
    pile: 'vermelha',
    genre: 'Synth-pop / 80s',
    hint: 'A bateria eletrônica rápida dos anos 80 e o sintetizador mais alegre de todos.',
    stems: [
      { number: 1, name: 'Bateria Eletrônica LinnDrum', category: 'drums', audioPath: '/audio/take-on-me/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Sintetizado', category: 'bass', audioPath: '/audio/take-on-me/2.mp3', unlocked: false },
      { number: 3, name: 'Sintetizador Rítmico de Fundo', category: 'synth', audioPath: '/audio/take-on-me/3.mp3', unlocked: false },
      { number: 4, name: 'Riff Principal de Teclado', category: 'synth', audioPath: '/audio/take-on-me/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Morten Harket (Agudos Extremos)', category: 'vocals', audioPath: '/audio/take-on-me/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'pelados-em-santos',
    cardCode: 'CARD-029',
    title: 'Pelados em Santos',
    artist: 'Mamonas Assassinas',
    releaseYear: 1995,
    youtubeViews: '90M Views',
    difficulty: 'dificil',
    difficultyLabel: 'Difícil (par 4)',
    pile: 'vermelha',
    genre: 'Rock Cômico / Brasil',
    hint: 'Mina, seus cabelo é da hora! O fenômeno meteórico de 1995 com sua Brasília Amarela.',
    stems: [
      { number: 1, name: 'Bateria Sérgio Reoli', category: 'drums', audioPath: '/audio/pelados-em-santos/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo Samuel Reoli', category: 'bass', audioPath: '/audio/pelados-em-santos/2.mp3', unlocked: false },
      { number: 3, name: 'Teclado Brega & Órgão', category: 'synth', audioPath: '/audio/pelados-em-santos/3.mp3', unlocked: false },
      { number: 4, name: 'Guitarra Bento Hinoto', category: 'guitar', audioPath: '/audio/pelados-em-santos/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Dinho', category: 'vocals', audioPath: '/audio/pelados-em-santos/5.mp3', unlocked: false },
    ]
  },
  {
    id: 'bohemian-rhapsody',
    cardCode: 'CARD-030',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    releaseYear: 1975,
    youtubeViews: '1.8B Views',
    difficulty: 'dificil',
    difficultyLabel: 'Difícil (par 5)',
    pile: 'vermelha',
    genre: 'Prog Rock / Ópera Rock',
    hint: 'A obra-prima do rock de 6 minutos com seção operística e solo lendário.',
    stems: [
      { number: 1, name: 'Bateria Roger Taylor', category: 'drums', audioPath: '/audio/bohemian-rhapsody/1.mp3', unlocked: true },
      { number: 2, name: 'Baixo John Deacon', category: 'bass', audioPath: '/audio/bohemian-rhapsody/2.mp3', unlocked: false },
      { number: 3, name: 'Piano Freddie Mercury', category: 'synth', audioPath: '/audio/bohemian-rhapsody/3.mp3', unlocked: false },
      { number: 4, name: 'Coros de Ópera & Guitarra Brian May', category: 'guitar', audioPath: '/audio/bohemian-rhapsody/4.mp3', unlocked: false },
      { number: 5, name: 'Voz Principal Freddie Mercury', category: 'vocals', audioPath: '/audio/bohemian-rhapsody/5.mp3', unlocked: false },
    ]
  }
];

// Helper para gerar o baralho completo expandido de 200 cartas
export function getComplete200Deck(): Song[] {
  // Lista base inicial com 30 super hits detalhados
  const baseSongs = [...ALL_DECK_SONGS];
  
  // Lista de 170 grandes sucessos complementares para totalizar 200 cartas de tabuleiro
  const additionalTitles = [
    // 🟢 Pilha Verde (Fácil / Par 1-2)
    { code: 'CARD-031', title: 'Faroeste Caboclo', artist: 'Legião Urbana', year: 1987, views: '150M', diff: 'facil', par: 'Fácil (par 2)', pile: 'verde', genre: 'Rock Nacional' },
    { code: 'CARD-032', title: 'Shape of You', artist: 'Ed Sheeran', year: 2017, views: '6.2B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Pop' },
    { code: 'CARD-033', title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', year: 2014, views: '5.2B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Funk Pop' },
    { code: 'CARD-034', title: 'Anna Júlia', artist: 'Los Hermanos', year: 1999, views: '85M', diff: 'facil', par: 'Fácil (par 2)', pile: 'verde', genre: 'Pop Rock' },
    { code: 'CARD-035', title: 'Despacito', artist: 'Luis Fonsi ft. Daddy Yankee', year: 2017, views: '8.4B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Reggaeton' },
    { code: 'CARD-036', title: 'Mulher de Fases', artist: 'Raimundos', year: 1999, views: '95M', diff: 'facil', par: 'Fácil (par 2)', pile: 'verde', genre: 'Hardcore / Brasil' },
    { code: 'CARD-037', title: 'Vou Deixar', artist: 'Skank', year: 2003, views: '80M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Pop Rock' },
    { code: 'CARD-038', title: 'Seven Nation Army', artist: 'The White Stripes', year: 2003, views: '700M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Garage Rock' },
    { code: 'CARD-039', title: 'Camarote', artist: 'Wesley Safadão', year: 2015, views: '200M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Forró Eletrônico' },
    { code: 'CARD-040', title: 'Eye of the Tiger', artist: 'Survivor', year: 1982, views: '1.2B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Hard Rock' },
    { code: 'CARD-041', title: 'Envolvimento', artist: 'MC Loma e as Gêmeas Lacração', year: 2018, views: '300M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Brega Funk' },
    { code: 'CARD-042', title: 'Beat It', artist: 'Michael Jackson', year: 1982, views: '1.1B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Pop Rock' },
    { code: 'CARD-043', title: 'Show das Poderosas', artist: 'Anitta', year: 2013, views: '170M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Funk Pop' },
    { code: 'CARD-044', title: 'Wonderwall', artist: 'Oasis', year: 1995, views: '950M', diff: 'facil', par: 'Fácil (par 2)', pile: 'verde', genre: 'Britpop' },
    { code: 'CARD-045', title: 'Coração Cachorro', artist: 'Ávine Vinny & Matheus Fernandes', year: 2021, views: '180M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Forró Pop' },
    { code: 'CARD-046', title: 'Another One Bites the Dust', artist: 'Queen', year: 1980, views: '650M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Funk Rock' },
    { code: 'CARD-047', title: 'Batom de Cereja', artist: 'Israel & Rodolffo', year: 2021, views: '450M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Sertanejo' },
    { code: 'CARD-048', title: 'Hips Don\'t Lie', artist: 'Shakira ft. Wyclef Jean', year: 2006, views: '1.4B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Latin Pop' },
    { code: 'CARD-049', title: 'Amor de Que', artist: 'Pabllo Vittar', year: 2019, views: '140M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Brega Pop' },
    { code: 'CARD-050', title: 'Sweet Child O\' Mine', artist: 'Guns N\' Roses', year: 1987, views: '1.7B', diff: 'facil', par: 'Fácil (par 2)', pile: 'verde', genre: 'Hard Rock' },
    { code: 'CARD-051', title: 'Atrasadinha', artist: 'Felipe Araújo & Ferrugem', year: 2018, views: '490M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Pagonejo' },
    { code: 'CARD-052', title: 'Levitating', artist: 'Dua Lipa', year: 2020, views: '950M', diff: 'facil', par: 'Fácil (par 2)', pile: 'verde', genre: 'Disco Pop' },
    { code: 'CARD-053', title: 'Malandramente', artist: 'Dennis DJ ft. MCs Nandinho & Nego Bam', year: 2016, views: '120M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Funk' },
    { code: 'CARD-054', title: 'Believer', artist: 'Imagine Dragons', year: 2017, views: '2.7B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Pop Rock' },
    { code: 'CARD-055', title: 'Cerveja de Garrafa', artist: 'Atitude 67', year: 2017, views: '280M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Pagode' },
    { code: 'CARD-056', title: 'Sugar', artist: 'Maroon 5', year: 2014, views: '4.1B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Pop' },
    { code: 'CARD-057', title: 'Pipoco', artist: 'Ana Castela ft. Melody & Chris no Beat', year: 2022, views: '320M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Agroplay' },
    { code: 'CARD-058', title: 'Gangnam Style', artist: 'PSY', year: 2012, views: '5.2B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'K-Pop / Dance' },
    { code: 'CARD-059', title: 'Deu Onda', artist: 'MC G15', year: 2016, views: '380M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Funk' },
    { code: 'CARD-060', title: 'Old Town Road', artist: 'Lil Nas X ft. Billy Ray Cyrus', year: 2019, views: '1.3B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Country Rap' },
    { code: 'CARD-061', title: 'Liberdade Provisória', artist: 'Henrique & Juliano', year: 2019, views: '450M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Sertanejo' },
    { code: 'CARD-062', title: 'Baby', artist: 'Justin Bieber ft. Ludacris', year: 2010, views: '3.1B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Teen Pop' },
    { code: 'CARD-063', title: 'Hear Me Now', artist: 'Alok, Bruno Martini ft. Zeeba', year: 2016, views: '650M', diff: 'facil', par: 'Fácil (par 2)', pile: 'verde', genre: 'Deep House' },
    { code: 'CARD-064', title: 'Bad Romance', artist: 'Lady Gaga', year: 2009, views: '1.8B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Electropop' },
    { code: 'CARD-065', title: 'Dona de Mim', artist: 'IZA', year: 2018, views: '260M', diff: 'facil', par: 'Fácil (par 2)', pile: 'verde', genre: 'Pop / R&B Brasil' },
    { code: 'CARD-066', title: 'In the End', artist: 'Linkin Park', year: 2000, views: '1.8B', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Nu Metal' },
    { code: 'CARD-067', title: 'Jenifer', artist: 'Gabriel Diniz', year: 2018, views: '360M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Forró Pop' },
    { code: 'CARD-068', title: 'Toxic', artist: 'Britney Spears', year: 2003, views: '700M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Dance-pop' },
    { code: 'CARD-069', title: 'Sorte Grande (Poeira)', artist: 'Ivete Sangalo', year: 2002, views: '60M', diff: 'facil', par: 'Fácil (par 1)', pile: 'verde', genre: 'Axé' },
    { code: 'CARD-070', title: 'Viva La Vida', artist: 'Coldplay', year: 2008, views: '950M', diff: 'facil', par: 'Fácil (par 2)', pile: 'verde', genre: 'Baroque Pop' },

    // 🟡 Pilha Amarela (Média / Par 3)
    { code: 'CARD-071', title: 'Pais e Filhos', artist: 'Legião Urbana', year: 1989, views: '120M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Rock Nacional' },
    { code: 'CARD-072', title: 'Locked Out of Heaven', artist: 'Bruno Mars', year: 2012, views: '1.1B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Pop Funk' },
    { code: 'CARD-073', title: 'Cazuza - Exagerado', artist: 'Cazuza', year: 1985, views: '90M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Pop Rock Brasil' },
    { code: 'CARD-074', title: 'Clocks', artist: 'Coldplay', year: 2002, views: '450M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Alternative Rock' },
    { code: 'CARD-075', title: 'Milla', artist: 'Netinho', year: 1996, views: '50M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Axé 90' },
    { code: 'CARD-076', title: 'Flowers', artist: 'Miley Cyrus', year: 2023, views: '800M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Disco Pop' },
    { code: 'CARD-077', title: 'Primeiros Erros', artist: 'Capital Inicial', year: 2000, views: '150M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Rock Acústico' },
    { code: 'CARD-078', title: 'Californication', artist: 'Red Hot Chili Peppers', year: 1999, views: '1.2B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Funk Rock' },
    { code: 'CARD-079', title: 'Infiel', artist: 'Marília Mendonça', year: 2015, views: '600M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Feminejo' },
    { code: 'CARD-080', title: 'Somebody That I Used to Know', artist: 'Gotye ft. Kimbra', year: 2011, views: '2.3B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Indie Pop' },
    { code: 'CARD-081', title: 'O Segundo Sol', artist: 'Nando Reis / Cássia Eller', year: 1999, views: '110M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'MPB / Rock' },
    { code: 'CARD-082', title: 'Hotel California', artist: 'Eagles', year: 1976, views: '1.5B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Classic Rock' },
    { code: 'CARD-083', title: 'Metamorfose Ambulante', artist: 'Raul Seixas', year: 1973, views: '70M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Rock Clássico Brasil' },
    { code: 'CARD-084', title: 'Feel Good Inc.', artist: 'Gorillaz', year: 2005, views: '1.3B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Alternative / Hip Hop' },
    { code: 'CARD-085', title: 'La Belle de Jour', artist: 'Alceu Valença', year: 1992, views: '95M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Frevo / MPB' },
    { code: 'CARD-086', title: 'As It Was', artist: 'Harry Styles', year: 2022, views: '800M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Synth-pop' },
    { code: 'CARD-087', title: 'Burguesinha', artist: 'Seu Jorge', year: 2007, views: '100M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Samba Pop' },
    { code: 'CARD-088', title: 'Wake Me Up', artist: 'Avicii ft. Aloe Blacc', year: 2013, views: '2.4B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'EDM / Country' },
    { code: 'CARD-089', title: 'Maneiras', artist: 'Zeca Pagodinho', year: 1997, views: '80M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Samba' },
    { code: 'CARD-090', title: 'Dancing Queen', artist: 'ABBA', year: 1976, views: '900M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Euro Disco' },
    { code: 'CARD-091', title: 'Céu Azul', artist: 'Charlie Brown Jr.', year: 2011, views: '250M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Rock Nacional' },
    { code: 'CARD-092', title: 'Crazy in Love', artist: 'Beyoncé ft. Jay-Z', year: 2003, views: '800M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'R&B / Pop' },
    { code: 'CARD-093', title: 'Trem-Bala', artist: 'Ana Vilela', year: 2016, views: '230M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Nova MPB' },
    { code: 'CARD-094', title: 'Radioactive', artist: 'Imagine Dragons', year: 2012, views: '1.6B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Alternative Rock' },
    { code: 'CARD-095', title: 'Pesadão', artist: 'IZA ft. Marcelo Falcão', year: 2017, views: '380M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Pop / Reggae' },
    { code: 'CARD-096', title: 'Livin\' on a Prayer', artist: 'Bon Jovi', year: 1986, views: '1.2B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Glam Metal' },
    { code: 'CARD-097', title: 'Ainda Gosto Dela', artist: 'Skank ft. Negra Li', year: 2008, views: '140M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Pop Rock' },
    { code: 'CARD-098', title: 'Cheap Thrills', artist: 'Sia ft. Sean Paul', year: 2016, views: '1.9B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Pop Dance' },
    { code: 'CARD-099', title: 'Como Nossos Pais', artist: 'Elis Regina', year: 1976, views: '80M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'MPB' },
    { code: 'CARD-100', title: 'Lose Yourself', artist: 'Eminem', year: 2002, views: '1.5B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Hip Hop' },
    { code: 'CARD-101', title: 'Ai Já Era', artist: 'Jorge & Mateus', year: 2010, views: '180M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Sertanejo' },
    { code: 'CARD-102', title: 'Pumped Up Kicks', artist: 'Foster the People', year: 2010, views: '1.1B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Indie Pop' },
    { code: 'CARD-103', title: 'Não Quero Dinheiro', artist: 'Tim Maia', year: 1971, views: '130M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Soul / Samba' },
    { code: 'CARD-104', title: 'Starboy', artist: 'The Weeknd ft. Daft Punk', year: 2016, views: '2.4B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'R&B / Electro' },
    { code: 'CARD-105', title: 'Meu Abrigo', artist: 'Melim', year: 2017, views: '430M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Reggae Pop' },
    { code: 'CARD-106', title: 'Hey Jude', artist: 'The Beatles', year: 1968, views: '400M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Classic Rock' },
    { code: 'CARD-107', title: 'Tijolinho por Tijolinho', artist: 'Enzo Rabelo ft. Zé Felipe', year: 2018, views: '400M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Sertanejo Pop' },
    { code: 'CARD-108', title: 'Royals', artist: 'Lorde', year: 2013, views: '1.0B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Art Pop' },
    { code: 'CARD-109', title: 'Anunciação', artist: 'Alceu Valença', year: 1983, views: '150M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Forró / MPB' },
    { code: 'CARD-110', title: 'Don\'t Start Now', artist: 'Dua Lipa', year: 2019, views: '700M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Nu-Disco' },
    { code: 'CARD-111', title: 'O Sol', artist: 'Vitor Kley', year: 2017, views: '310M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Pop Good Vibes' },
    { code: 'CARD-112', title: 'Mr. Brightside', artist: 'The Killers', year: 2003, views: '600M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Indie Rock' },
    { code: 'CARD-113', title: 'Propaganda', artist: 'Jorge & Mateus', year: 2018, views: '450M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Sertanejo' },
    { code: 'CARD-114', title: 'Umbrella', artist: 'Rihanna ft. Jay-Z', year: 2007, views: '1.1B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'R&B / Pop' },
    { code: 'CARD-115', title: 'Acorda Pedrinho', artist: 'Jovem Dionisio', year: 2022, views: '60M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Indie Pop' },
    { code: 'CARD-116', title: 'Sweet Dreams (Are Made of This)', artist: 'Eurythmics', year: 1983, views: '900M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Synth-pop' },
    { code: 'CARD-117', title: 'Deixa', artist: 'Lagum ft. Ana Gabriela', year: 2018, views: '160M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Pop Reggae' },
    { code: 'CARD-118', title: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper', year: 1983, views: '1.2B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: '80s Pop' },
    { code: 'CARD-119', title: 'Hear Me Now', artist: 'Alok', year: 2016, views: '650M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Brazilian Bass' },
    { code: 'CARD-120', title: 'Africa', artist: 'Toto', year: 1982, views: '1.0B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Soft Rock' },
    { code: 'CARD-121', title: 'Sino Dourado', artist: 'Ana Castela', year: 2023, views: '190M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Sertanejo' },
    { code: 'CARD-122', title: 'Thunderstruck', artist: 'AC/DC', year: 1990, views: '1.5B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Hard Rock' },
    { code: 'CARD-123', title: 'Chão de Giz', artist: 'Zé Ramalho', year: 1978, views: '90M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'MPB / Folk' },
    { code: 'CARD-124', title: 'Blame', artist: 'Calvin Harris ft. John Newman', year: 2014, views: '900M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'EDM' },
    { code: 'CARD-125', title: 'Mulher Feita', artist: 'Projota', year: 2017, views: '280M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Rap Acústico' },
    { code: 'CARD-126', title: 'Shallow', artist: 'Lady Gaga & Bradley Cooper', year: 2018, views: '1.7B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Folk Pop' },
    { code: 'CARD-127', title: 'Ainda É Cedo', artist: 'Legião Urbana', year: 1985, views: '80M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Post-Punk Brasil' },
    { code: 'CARD-128', title: 'Rather Be', artist: 'Clean Bandit ft. Jess Glynne', year: 2014, views: '850M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Deep House' },
    { code: 'CARD-129', title: 'Canteiros', artist: 'Fagner', year: 1977, views: '40M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'MPB' },
    { code: 'CARD-130', title: 'Titanium', artist: 'David Guetta ft. Sia', year: 2011, views: '1.8B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Electro House' },
    { code: 'CARD-131', title: 'Sonífera Ilha', artist: 'Titãs', year: 1984, views: '45M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Ska / Rock' },
    { code: 'CARD-132', title: 'Bad Blood', artist: 'Taylor Swift', year: 2014, views: '1.6B', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Pop' },
    { code: 'CARD-133', title: 'Amor Pra Recomeçar', artist: 'Frejat', year: 2001, views: '60M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Pop Rock' },
    { code: 'CARD-134', title: 'Wake Me Up Before You Go-Go', artist: 'Wham!', year: 1984, views: '550M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: '80s Pop' },
    { code: 'CARD-135', title: 'Só os Loucos Sabem', artist: 'Charlie Brown Jr.', year: 2010, views: '300M', diff: 'medio', par: 'Médio (par 3)', pile: 'amarela', genre: 'Rock Nacional' },

    // 🔴 Pilha Vermelha (Difícil / Par 4-5)
    { code: 'CARD-136', title: 'Construção', artist: 'Chico Buarque', year: 1971, views: '45M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'MPB Sinfônica' },
    { code: 'CARD-137', title: 'Around the World', artist: 'Daft Punk', year: 1997, views: '180M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'French House' },
    { code: 'CARD-138', title: 'Vapor Barato', artist: 'Gal Costa', year: 1971, views: '30M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Tropicália' },
    { code: 'CARD-139', title: 'Clint Eastwood', artist: 'Gorillaz', year: 2001, views: '750M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Trip Hop' },
    { code: 'CARD-140', title: 'Roda Viva', artist: 'Chico Buarque', year: 1968, views: '35M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Samba / MPB' },
    { code: 'CARD-141', title: 'Stairway to Heaven', artist: 'Led Zeppelin', year: 1971, views: '500M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Hard Rock' },
    { code: 'CARD-142', title: 'Sampa', artist: 'Caetano Veloso', year: 1978, views: '50M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'MPB Clássica' },
    { code: 'CARD-143', title: 'Blue Monday', artist: 'New Order', year: 1983, views: '200M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Synth-pop' },
    { code: 'CARD-144', title: 'Tarde em Itapoã', artist: 'Vinicius de Moraes & Toquinho', year: 1971, views: '25M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Bossa Nova' },
    { code: 'CARD-145', title: 'Money', artist: 'Pink Floyd', year: 1973, views: '150M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Prog Rock (7/4 Time)' },
    { code: 'CARD-146', title: 'Tropicália', artist: 'Caetano Veloso', year: 1968, views: '20M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Tropicália' },
    { code: 'CARD-147', title: 'Levels', artist: 'Avicii', year: 2011, views: '700M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Progressive House' },
    { code: 'CARD-148', title: 'Carinhoso', artist: 'Pixinguinha', year: 1937, views: '60M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Choro / MPB' },
    { code: 'CARD-149', title: 'Midnight City', artist: 'M83', year: 2011, views: '450M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Synthwave' },
    { code: 'CARD-150', title: 'Gita', artist: 'Raul Seixas', year: 1974, views: '40M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Rock Místico Brasil' },
    { code: 'CARD-151', title: 'Harder, Better, Faster, Stronger', artist: 'Daft Punk', year: 2001, views: '250M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Electronic' },
    { code: 'CARD-152', title: 'Trem das Onze', artist: 'Demonios da Garoa', year: 1964, views: '40M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Samba Paulista' },
    { code: 'CARD-153', title: 'Enjoy the Silence', artist: 'Depeche Mode', year: 1990, views: '380M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Synth-pop' },
    { code: 'CARD-154', title: 'Cálice', artist: 'Chico Buarque & Milton Nascimento', year: 1978, views: '35M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'MPB / Protesto' },
    { code: 'CARD-155', title: 'Animals', artist: 'Martin Garrix', year: 2013, views: '1.7B', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Big Room House' },
    { code: 'CARD-156', title: 'Disritmia', artist: 'Martinho da Vila', year: 1974, views: '30M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Partido Alto' },
    { code: 'CARD-157', title: 'Sultans of Swing', artist: 'Dire Straits', year: 1978, views: '550M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Roots Rock' },
    { code: 'CARD-158', title: 'O Bêbado e a Equilibrista', artist: 'Elis Regina', year: 1979, views: '25M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Samba Choro' },
    { code: 'CARD-159', title: 'Stereo Love', artist: 'Edward Maya & Vika Jigulina', year: 2009, views: '650M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Eurodance' },
    { code: 'CARD-160', title: 'Detalhes', artist: 'Roberto Carlos', year: 1971, views: '70M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Balada Brasil' },
    { code: 'CARD-161', title: 'Bangarang', artist: 'Skrillex ft. Sirah', year: 2011, views: '1.1B', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Dubstep' },
    { code: 'CARD-162', title: 'Aquarela', artist: 'Toquinho', year: 1983, views: '180M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'MPB / Violão' },
    { code: 'CARD-163', title: 'Superstition', artist: 'Stevie Wonder', year: 1972, views: '250M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Funk / Clavinet' },
    { code: 'CARD-164', title: 'Mas Que Nada', artist: 'Jorge Ben Jor / Sergio Mendes', year: 1963, views: '95M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Samba Rock' },
    { code: 'CARD-165', title: 'Scatman (Ski-Ba-Bop-Ba-Dop-Bop)', artist: 'Scatman John', year: 1994, views: '200M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Eurodance' },
    { code: 'CARD-166', title: 'As Rosas Não Falam', artist: 'Cartola', year: 1976, views: '40M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Samba de Raiz' },
    { code: 'CARD-167', title: 'Radio Ga Ga', artist: 'Queen', year: 1984, views: '400M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Synth Rock' },
    { code: 'CARD-168', title: 'Panis et Circenses', artist: 'Os Mutantes', year: 1968, views: '15M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Rock Psicodélico' },
    { code: 'CARD-169', title: 'Sandstorm', artist: 'Darude', year: 1999, views: '300M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Trance Instrumental' },
    { code: 'CARD-170', title: 'Canto das Três Raças', artist: 'Clara Nunes', year: 1976, views: '30M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Samba / Afoxé' },
    { code: 'CARD-171', title: 'One More Time', artist: 'Daft Punk', year: 2000, views: '550M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'French House' },
    { code: 'CARD-172', title: 'Chove Chuva', artist: 'Jorge Ben Jor', year: 1963, views: '25M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Samba Bossa' },
    { code: 'CARD-173', title: 'Clocks', artist: 'Coldplay', year: 2002, views: '450M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Piano Rock' },
    { code: 'CARD-174', title: 'Wave', artist: 'Tom Jobim', year: 1967, views: '30M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Bossa Instrumental' },
    { code: 'CARD-175', title: 'Kernkraft 400', artist: 'Zombie Nation', year: 1999, views: '150M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Techno Stadium' },
    { code: 'CARD-176', title: 'Travessia', artist: 'Milton Nascimento', year: 1967, views: '20M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Clube da Esquina' },
    { code: 'CARD-177', title: 'Satisfaction', artist: 'Benny Benassi', year: 2002, views: '160M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Electro House' },
    { code: 'CARD-178', title: 'Aquele Abraço', artist: 'Gilberto Gil', year: 1969, views: '25M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Samba Tropicália' },
    { code: 'CARD-179', title: 'Pump Up the Jam', artist: 'Technotronic', year: 1989, views: '380M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Hip House' },
    { code: 'CARD-180', title: 'Maria Maria', artist: 'Milton Nascimento', year: 1978, views: '45M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'MPB / Coral' },
    { code: 'CARD-181', title: 'Tears in Heaven', artist: 'Eric Clapton', year: 1992, views: '350M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Acoustic Rock' },
    { code: 'CARD-182', title: 'Flor de Lis', artist: 'Djavan', year: 1976, views: '55M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Samba / Jazz Brasil' },
    { code: 'CARD-183', title: 'The Rhythm of the Night', artist: 'Corona', year: 1993, views: '320M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Eurodance 90' },
    { code: 'CARD-184', title: 'Sina', artist: 'Djavan', year: 1982, views: '45M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Soul / MPB' },
    { code: 'CARD-185', title: 'Rapture', artist: 'Blondie', year: 1981, views: '110M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'New Wave / Disco Rap' },
    { code: 'CARD-186', title: 'Samurai', artist: 'Djavan ft. Stevie Wonder', year: 1982, views: '65M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Pop Soul Brasil' },
    { code: 'CARD-187', title: 'The Final Countdown', artist: 'Europe', year: 1986, views: '1.2B', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Synth Rock' },
    { code: 'CARD-188', title: 'Oceano', artist: 'Djavan', year: 1989, views: '90M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'MPB / Balada' },
    { code: 'CARD-189', title: 'Popcorn', artist: 'Hot Butter / Gershon Kingsley', year: 1972, views: '80M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Moog Synth Classic' },
    { code: 'CARD-190', title: 'Vou Festejar', artist: 'Beth Carvalho', year: 1978, views: '50M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Samba / Carnaval' },
    { code: 'CARD-191', title: 'Macarena', artist: 'Los del Río', year: 1993, views: '400M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Latin Dance' },
    { code: 'CARD-192', title: 'Cota Não É Esmola', artist: 'Bia Ferreira', year: 2018, views: '35M', diff: 'dificil', par: 'Difícil (par 5)', pile: 'vermelha', genre: 'Slam / Soul Brasil' },
    { code: 'CARD-193', title: 'What is Love', artist: 'Haddaway', year: 1993, views: '350M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Eurodance 90' },
    { code: 'CARD-194', title: 'Mulheres', artist: 'Martinho da Vila', year: 1995, views: '85M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Samba Romântico' },
    { code: 'CARD-195', title: 'Cotton Eye Joe', artist: 'Rednex', year: 1994, views: '250M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Country Dance' },
    { code: 'CARD-196', title: 'Linha do Equador', artist: 'Djavan', year: 1992, views: '70M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'MPB / Jazz' },
    { code: 'CARD-197', title: 'Scatman\'s World', artist: 'Scatman John', year: 1995, views: '140M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Eurodance' },
    { code: 'CARD-198', title: 'Trem das Sete', artist: 'Raul Seixas', year: 1974, views: '30M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Folk Rock Brasil' },
    { code: 'CARD-199', title: 'Axel F (Crazy Frog / Beverly Hills)', artist: 'Harold Faltermeyer', year: 1984, views: '4.5B', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: '80s Synth Theme' },
    { code: 'CARD-200', title: 'O Canto da Cidade', artist: 'Daniela Mercury', year: 1992, views: '60M', diff: 'dificil', par: 'Difícil (par 4)', pile: 'vermelha', genre: 'Axé / Samba-Reggae' }
  ];

  // Gera os 170 objetos com seus 5 stems estruturados
  const generatedSongs: Song[] = additionalTitles.map((t, idx) => {
    const fallbackSlug = (idx % 10 === 0) ? 'blinding-lights' 
      : (idx % 10 === 1) ? 'party-rock-anthem' 
      : (idx % 10 === 2) ? 'every-breath-you-take'
      : (idx % 10 === 3) ? 'bad-guy'
      : (idx % 10 === 4) ? 'counting-stars'
      : (idx % 10 === 5) ? 'roar'
      : (idx % 10 === 6) ? 'born-this-way'
      : (idx % 10 === 7) ? 'sweet-home-alabama'
      : (idx % 10 === 8) ? 'hotline-bling'
      : 'moves-like-jagger';

    return {
      id: t.title.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-'),
      cardCode: t.code,
      title: t.title,
      artist: t.artist,
      releaseYear: t.year,
      youtubeViews: `${t.views} Views`,
      difficulty: t.diff as any,
      difficultyLabel: t.par,
      pile: t.pile as any,
      genre: t.genre,
      hint: `Grande clássico (${t.year}) - ${t.genre}.`,
      stems: [
        { number: 1, name: 'Bateria / Percussão', category: 'drums', audioPath: `/audio/${fallbackSlug}/1.mp3`, unlocked: true },
        { number: 2, name: 'Baixo / Groove', category: 'bass', audioPath: `/audio/${fallbackSlug}/2.mp3`, unlocked: false },
        { number: 3, name: 'Harmonia / Base', category: 'synth', audioPath: `/audio/${fallbackSlug}/3.mp3`, unlocked: false },
        { number: 4, name: 'Instrumental Completo', category: 'guitar', audioPath: `/audio/${fallbackSlug}/4.mp3`, unlocked: false },
        { number: 5, name: 'Voz Principal & Arranjo', category: 'vocals', audioPath: `/audio/${fallbackSlug}/5.mp3`, unlocked: false },
      ]
    };
  });

  return [...baseSongs, ...generatedSongs];
}

export const COMPLETE_200_DECK: Song[] = getComplete200Deck();
